### ISSUE TITLE
hello-ribbon-springboot does not have ribbon example

### ISSUE THREAD

**Issue by rblazquez** [fabric8io/kubeflix#100]
Cannot see any ribbon related code on kubeflix/examples/hello-world/hello-ribbon-springboot/

I see hystrix things but nothing on ribbon.

**Comment by iocanel** [comment]
Ribbon is used under the hood via resttemplate.

**Comment by rblazquez** [comment]
ohh ... thanks for the information but that way it becomes dificult to understand how to use it in my own project. I am trying to build the same thing (spring-boot + kubernetes + ribbon) but i am a bit lost about how the different pieces fit together.

**Comment by iocanel** [comment]
I closed this issue, cause I don't think there is anything more we can do here.
