### ISSUE TITLE
upgrade the kubernetes-client and mockwebserver/groovy/spock dependencies

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubeflix#107]
looks like kubeflix is using a really old version of kubernetes-client. Upgrading caused issues with mockwebserver - so maybe that needs to migrate to the io.fabric8 one? 

Not totally sure - figure @iocanel you'd know better :)

**Comment by jstrachan** [comment]
see errors if we try: https://github.com/fabric8io/kubeflix/pull/106

**Comment by iocanel** [comment]
This has been already fixed as of https://github.com/fabric8io/kubeflix/commit/f837d26998183ad52d764bfceb6f8323ffd32ff7
