### ISSUE TITLE
Error deploying in Openshift Origin 1.3

### ISSUE THREAD

**Issue by rafabene** [fabric8io/kubeflix#121]
The following error happened when I tried to deploy in Openshift 1.3 using 'oc create -f http://central.maven.org/maven2/io/fabric8/kubeflix/packages/kubeflix/1.0.20/kubeflix-1.0.20-kubernetes.yml'

`":"kubeflix","project":"kubeflix","provider":"fabric8","version":"1.0.20"}: `selector` does not match template `labels`
Error from server: Deployment.extensions "turbine-server" is invalid: spec.template.metadata.labels: Invalid value: {"group":"io.fabric8.kubeflix","package":"kubeflix","project":"kubeflix","provider":"fabric8","version":"1.0.20"}: `selector` does not match template `labels``

**Comment by iocanel** [comment]
May be a side effect of the upgrade to the new f-m-p. Will take a look.

**Comment by wrichter** [comment]
Same for the -openshift variant (in OpenShift Enterprise 3.3) - first the oc command complains about duplicate objects, then the event trail show the same error message as above:

$ oc create -f http://central.maven.org/maven2/io/fabric8/kubeflix/packages/kubeflix/1.0.20/kubeflix-1.0.20-openshift.json
serviceaccount "ribbon" created
serviceaccount "turbine" created
service "hystrix-dashboard" created
service "turbine-server" created
deploymentconfig "hystrix-dashboard" created
deploymentconfig "turbine-server" created
Error from server: serviceaccounts "turbine" already exists
Error from server: services "turbine-server" already exists
Error from server: deploymentconfigs "turbine-server" already exists
$ oc get events
FIRSTSEEN   LASTSEEN   COUNT     NAME                KIND               SUBOBJECT   TYPE      REASON                     SOURCE                           MESSAGE
2s          2s         2         hystrix-dashboard   DeploymentConfig               Warning   DeploymentCreationFailed   {deploymentconfig-controller }   Couldn't deploy version 1: ReplicationController "hystrix-dashboard-1" is invalid: spec.template.metadata.labels: Invalid value: {"deployment":"hystrix-dashboard-1","deploymentconfig":"hystrix-dashboard","group":"io.fabric8.kubeflix","package":"kubeflix","project":"kubeflix","provider":"fabric8","version":"1.0.20"}: `selector` does not match template `labels`
2s          2s         2         turbine-server      DeploymentConfig               Warning   DeploymentCreationFailed   {deploymentconfig-controller }   Couldn't deploy version 1: ReplicationController "turbine-server-1" is invalid: spec.template.metadata.labels: Invalid value: {"deployment":"turbine-server-1","deploymentconfig":"turbine-server","group":"io.fabric8.kubeflix","package":"kubeflix","project":"kubeflix","provider":"fabric8","version":"1.0.20"}: `selector` does not match template `labels`

**Comment by iocanel** [comment]
So there are two issues here:

i) in openshift you should use: http://central.maven.org/maven2/io/fabric8/kubeflix/packages/kubeflix/1.0.20/kubeflix-1.0.20-openshift.yml
ii) there is a bug in the aggregator package, which will be addressed shortly.

**Comment by iocanel** [comment]
This can be closed now
