### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/kubeflix#137]
Just tried to build this following the readme

INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Kubeflix :: Examples :: LoanBroker :: Broker 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.fabric8.kubeflix:ribbon-discovery:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Kubeflix :: Examples :: Loan Broker ................ SUCCESS [  1.243 s]
[INFO] Kubeflix :: Examples :: LoanBroker :: Credit Bureau  SUCCESS [ 25.254 s]
[INFO] Kubeflix :: Examples :: LoanBroker :: Bank ......... SUCCESS [ 13.897 s]
[INFO] Kubeflix :: Examples :: LoanBroker :: Broker ....... FAILURE [  0.033 s]
[INFO] Kubeflix :: Examples :: LoanBroker :: Genearator ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.511 s
[INFO] Finished at: 2016-10-24T17:04:50+01:00
[INFO] Final Memory: 71M/1104M
[ERROR] Failed to execute goal on project loanbroker-broker: Could not resolve dependencies for project io.fabric8.kubeflix.examples:loanbroker-broker:jar:1.0-SNAPSHOT: Failure to find io.fabric8.kubeflix:ribbon-discovery:jar:1.0-SNAPSHOT in https://repo.spring.io/libs-release was cached in the local repository, resolution will not be reattempted until the update interval of spring-releases has elapsed or updates are forced -> [Help 1]

**Comment by jstrachan** [comment]
I think you need to do a build in the top directory first to get the dependencies for the example built?
