### ISSUE TITLE
Fixed version build without examples

### ISSUE THREAD

**Issue by stefaneg** [fabric8io/kubeflix#161]
I'm wrapping my head around how to get this tool into our configuration management. What I'm looking for:

a. Have a defined and fixed version of all libraries deployed (no snapshots).
b. Use defined and fixed version of all maven plugins (or skip them all together and use dockerfiles directly if possible)
b. Skip all examples. Only deploy turbine, appropriate discovery modules and hystrix dashboard.
c. Use internal docker repo.
d. Rely on published builds through maven central (no local build/test).

Any thoughts?

**Comment by iocanel** [comment]
All maven artifacts are available on maven central and docker images on dockerhub.

Kubernetes/Openshift manifests are also availble as maven artifacts on central:

http://repo1.maven.org/maven2/io/fabric8/kubeflix/turbine-server/1.0.26/
http://repo1.maven.org/maven2/io/fabric8/kubeflix/hystrix-dashboard/1.0.26/

**Comment by stefaneg** [comment]
Yes. My current strategy is create a maven project pulling in those manifest/jar/war dependencies instead of building them, changing docker user to push to internal docker repo, and using the fabric8 maven docker build plugins to build and push docker images.

**Comment by iocanel** [comment]
So, can we close this?

**Comment by stefaneg** [comment]
Still looks non-trivial to me. My strategy mentioned above does not seem to be possible since the building of the docker images is coupled with the war maven project itself, so its not wired to download the war and then build a docker image like I expected. So it looks to me that the only viable option (without a lot of work) is to fork the kubeflix project, remove what I don't want from it, and build the thing from scratch for my deployments. The reason is the requirement for an internal docker repo. So it looks like I cannot get c. and d. at the same time like things are wired together.

**Comment by iocanel** [comment]
Can't you just pull the image from dockerhub and just push it to your internal repo? Do you have to build it from source?

**Comment by stefaneg** [comment]
Yes I probably can. I was under the impression that I had to build the docker image with the repository specified, but it seems that I can tag it independently. http://stackoverflow.com/questions/28349392/how-to-push-a-docker-image-to-a-private-repository

**Comment by iocanel** [comment]
Yay!
