### ISSUE TITLE
Hystrix dashboard v 1.4.9 buggy

### ISSUE THREAD

**Issue by stefaneg** [fabric8io/kubeflix#162]
https://github.com/Netflix/Hystrix/issues/827

1.4.13 does not have this issue.

**Comment by stefaneg** [comment]
All that is required to fix this is to update hystrix.version to 1.4.13 in pom.xml

**Comment by stefaneg** [comment]
Any chance this will be addressed? Was hoping I would not have to create a fork.

**Comment by iocanel** [comment]
@stefaneg: Can you please update your pull request and update to hystrix 1.5.3.?

**Comment by stefaneg** [comment]
Will do.

**Comment by stefaneg** [comment]
Done.

**Comment by iocanel** [comment]
@stefaneg: Thanks for the pull request. its now merged and we will release shortly.
