### ISSUE TITLE
new archetype for spring boot + hystrix we can include in the fabric8 forge wizard

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubeflix#3]
it'd be great to create a quickstart for folks wanting to write a microservice based on spring boot + RestTemplate + hystrix so we can do demos showing how to get started with kurbine and then run turbine etc

Adding a quickstart to this github organisation should do the trick:
https://github.com/fabric8-quickstarts

**Comment by davsclaus** [comment]
Yeah this would be cool. Also should hysterix/turbine et all not be a package in devops or ipaas so its easier to install?

Would be nice if we can get the fabric8 console to show more packages out of the box that can install with click "run".

**Comment by iocanel** [comment]
I agree we need to make it as easiest as possible to install.

However, I don't think that those apps should be move to devops or ipaas, simply because they are neither.

**Comment by christian-posta** [comment]
Is this the quick start that addresses this issue? https://github.com/fabric8io/ipaas-quickstarts/tree/master/quickstart/spring-boot/ribbon  

https://github.com/fabric8io/ipaas-quickstarts/tree/master/archetypes/spring-boot-ribbon-archetype

**Comment by davsclaus** [comment]
yeah the archetypes are created from the quickstarts. So there should be a 1:1

**Comment by iocanel** [comment]
We can close this one.
