### ISSUE TITLE
ribbon discovery for the credit-bureau doesn't work

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/kubeflix#50]
verify by running the demo and watching the hystrix circuit breaker report 100% failures. noticed this in demo @rajdavies and @jstrachan and i did this morning.

I have a fix coming in a sec.

**Comment by iocanel** [comment]
@christian-posta: so it was always using the fallback score?

**Comment by christian-posta** [comment]
I suppose so :)

On Fri, Mar 18, 2016 at 12:23 PM, Ioannis Canellos <notifications@github.com
> wrote:

> @christian-posta <https://github.com/christian-posta>: so it was always
> using the fallback score?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/kubeflix/issues/50#issuecomment-198507396>
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by iocanel** [comment]
I knew it! Why on earth would I get a score of 24 :-)

**Comment by iocanel** [comment]
great catch btw!

**Comment by christian-posta** [comment]
Well, you may still end up with a score of 24 :-D

On Fri, Mar 18, 2016 at 12:38 PM, Ioannis Canellos <notifications@github.com
> wrote:

> I knew it! Why on earth would I get a score of 24 :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/kubeflix/issues/50#issuecomment-198513389>
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by christian-posta** [comment]
Fixed with https://github.com/fabric8io/kubeflix/pull/51
