### ISSUE TITLE
look at providing a Kubernetes ConfigMap backed Archaius plugin

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/kubeflix#54]
https://github.com/Netflix/archaius

**Comment by iocanel** [comment]
@christian-posta: added on the spring-cloud-kubernetes side of things configmap support. This comes in 2 flavours:

- spring-boot integration with configmap (externalise application.yml to ConfigMap).
- spring-cloud-archaius integration with configap annotation based approach to intiialize archaius config by configmap.

I am wondering do we need a pure archaius/configmap integration (non-spring one)?

**Comment by christian-posta** [comment]
Crap I missed this notification! Let me give this a try :)

On Thursday, April 21, 2016, Ioannis Canellos <notifications@github.com>
wrote:

> @christian-posta <https://github.com/christian-posta>: added on the
> spring-cloud-kubernetes side of things configmap support. This comes in 2
> flavours:
>
>    - spring-boot integration with configmap (externalise application.yml
>    to ConfigMap).
>    - spring-cloud-archaius integration with configap annotation based
>    approach to intiialize archaius config by configmap.
>
> I am wondering do we need a pure archaius/configmap integration
> (non-spring one)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/kubeflix/issues/54#issuecomment-212821723>
>


-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by iocanel** [comment]
@christian-posta: happens to me all the time :-)
