### ISSUE TITLE
ribbon client side load balancer should filter out pods that are not 'Ready' 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubeflix#55]
so we get to reuse the readiness probe results

**Comment by iocanel** [comment]
@jstrachan: It seems that Kubernetes separates between "endpoint addresses" and "not ready endpoint addresses".  So from the ribbon discovery side we don't need to do anything at all.

Also experimented with adding a readiness probe in the loan broker example and it seems fine.

I'll add readiness probes to our existing examples and close the issue.

**Comment by jimmidyson** [comment]
Yeah as long as your using endpoints & not using service selectors then readiness will be taken care of for you by Kubernetes. Make sure that you handle coming/going of same pod via readiness, it's a repeated check that adds/removes pods from endpoints as they pass/fail readiness probes without restarting the pod (that would be the purpose of liveness probes).

**Comment by jstrachan** [comment]
awesome thanks!
