### ISSUE TITLE
project dependencies

### ISSUE THREAD

**Issue by mliu5715k** [fabric8io/kubeflix#56]
can someone list the dependencies for this project? The instructions are very brief, following it does not lead to successful builds 

I am getting this error which i assume is because i don't have fabric8 installed. ```[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (default-cli) on project turbine-server: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.14.2:build failed: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock' -> [Help 1]```

**Comment by iocanel** [comment]
To build the project you just need:

    mvn clean install

If you also need to create docker images and apply kubernetes configuration you need to configure some environment variables:

- DOCKER_HOST: Url to the docker daemon (e.g. tcp://localhost:2375).
- KUBERNETES_MASTER: Url to the cabernets api master (e.g. https://localhost:8443)

This might be helpful too: http://fabric8.io/guide/mavenPlugin.html

**Comment by mliu5715k** [comment]
Yes, i do need to create docker images and deploy it to k8, and of course, test some basic use cases for turbine/hystrix.
where do I configure the variables? my shell in osx already has them
```
bucky:~ mliu5715k$ echo $DOCKER_HOST
tcp://192.168.99.100:2376
bucky:~ mliu5715k$ echo $KUBERNETES_MASTER
http://172.17.8.101:8080
```

**Comment by iocanel** [comment]
You need to configure them wherever you are running the build from. 

If you are building from the command line, they need to be available as env variables (and they do seem to be). 

If you are building from within your IDE, then you need to set them there too.

**Comment by iocanel** [comment]
@mliu5715k: for future reference can you please comment on what was the cause of your issue?

**Comment by mliu5715k** [comment]
it turns out i had previous Docker and K8 environment variables that's pointing to something else. Thanks.
