### ISSUE TITLE
exported docker image but didn't work

### ISSUE THREAD

**Issue by mliu5715k** [fabric8io/kubeflix#63]
I got the hello-hystrix example working in my vagrant sandbox, but couldn't get them working in my own k8 cluster with the same exported docker images.
I curled the turbine server and only got the heartbeat, it appears the turbine server is not finding any valid streams. Can you guys help check my labels? Anything needed besides "hystrix.enabled: true"?  also is there any other config required inside the turbine server? what else do i need to check?

```
$ kubectl get svc hello-hystrix -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-04-01T17:19:15Z
  labels:
    app: laroc
    hystrix.enabled: "true"
    namespace: goc
  name: hello-hystrix
  namespace: laroc
  resourceVersion: "37218890"
  selfLink: /api/v1/namespaces/coral/services/hello-hystrix
  uid: dc267df9-f82d-11e5-bf65-0025b5360aff
spec:
  clusterIP: 192.168.0.38
  ports:
  - nodePort: 9203
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: laroc
    hystrix.enabled: "true"
    name: hello-hystrix
    namespace: goc
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

**Comment by iocanel** [comment]
@mliu5715k: Turbine discovery is using 2 tables hystrix.enabled: true and also hystrix.cluster: "default".

At this point no other value other than "default" will work for hysterix.cluster (its a known) issue.

Other than that the turbine server will need to use a service account that will allow the pod to at least query endpoints.

**Comment by mliu5715k** [comment]
lack of skydns was the cause see #65
