### ISSUE TITLE
using kubeflix to monitor hystrix sources from outside the kubernetes cluster

### ISSUE THREAD

**Issue by raffaelespazzoli** [fabric8io/kubeflix#92]
Hi,

I have a use case where we would like to deploy a hystrix console + turbine inside an OpenShift cluster to monitor hystrix sources that reside outside the cluster.
Is it possible to specify which turbine discovery policy to use?

Thanks
Raffaele

**Comment by iocanel** [comment]
No, currently there is no way to use a custom instance discovery implementation, but it shouldn't be hard to do so.

**Comment by iocanel** [comment]
Until, we get this sorted there is an alternative.

The alternative is to define kubernetes endpoints for the external resources. for example:

    apiVersion: v1
    kind: Endpoints
    metadata:
      labels:
        hystrix.enabled: "true"
      name: myendpoint
    subsets:
    - addresses:
      - ip: <add external ip here>
      ports:
      - port: 80
        protocol: "TCP"

**Comment by raffaelespazzoli** [comment]
This is a good approach, we can close this issue for me.
